### ISSUE TITLE
align_trim.py error using V3 scheme bed file

### ISSUE THREAD

**Issue by lzhwin** [artic-network/artic-ncov2019#31]
When we update to V3 primmer , if we use V3/nCoV-2019.scheme.bed. the align_trim step has an error occured as following:
 line 96, in find_primer
 closest = min([(abs(p['start'] - pos), p['start'] - pos, p) for p in bed if p['direction'] == direction], key=itemgetter(0))
ValueError: min() arg is an empty sequence
but if we change the bed file to  V1/nCoV-2019.scheme.bed or V3/nCoV-2019.bed , there're no error occured.
So, is there something wrong in my pipline?

**Comment by will-rowe** [comment]
This sounds like it might be due to an old version of the artic pipeline causing an incompatibility issue?

If updating to the most recent version of the pipeline doesn't work (`conda install -c bioconda artic`), can you post this as an issue on the [artic pipeline repository](https://github.com/artic-network/fieldbioinformatics) please

**Comment by will-rowe** [comment]
Marking resolved and closing - please reopen if not fixed or you have a further question.
