### ISSUE TITLE
how to change min reads depth for consensus assembly?

### ISSUE THREAD

**Issue by Shaokang123** [artic-network/artic-ncov2019#49]
From the documentation, any position that is not covered by at least 20 reads are marked as low coverage and changed to "N". If I want to tweak this parameter, say lower it to 15, which file and line I shall change for artic? Thank you for any help.

**Comment by Shaokang123** [comment]
May I ask if any one can help answer the question?

**Comment by bede** [comment]
At a glance, it looks like the following files will need editing 

```
margin_cons.py
make_depth_mask.py
vcf_filter.py
```

**Comment by will-rowe** [comment]
Sorry for the delay in getting back to you @Shaokang123 - I don't normally monitor this repo and the pipeline dev happens over at [artic pipeline](https://github.com/artic-network/fieldbioinformatics).

@bede is right - there is no global pipeline parameter for adjusting minimum read depth per reference base. I'm not sure of the reason to this but I guess it's because we mask out both low coverage bases with N, as well as using coverage during the variant filtering, so having one variable controlling these is a little misleading.

To decrease minimum read depth required per base, you need to adjust the `artic_make_depth_mask` command in the `minion.py` script - just add `--depth 15`. If you want to also change the minimum read depth for variant filtering, you will need to adjust what is happening in `vcf_filter.py`.

I think it would be useful to adjust the minimum read depth for the former case here, I'll make a PR to the pipeline repo. Hope this helps, let me know if it doesn't!

**Comment by nickloman** [comment]
I would be keen to see this as a configurable parameter to artic minion. However I would suggest people don't go lower than 20x!  Partiularly as nanopolish will not call anything below 20x.

**Comment by Shaokang123** [comment]
Great. Many thanks to all of you! Appreciate the help. @bede @will-rowe @nickloman

**Comment by laura-bankers** [comment]
Has there been any movement towards making min depth a configurable parameter to artic minion --medaka? Given all of the recent conversations in the public health community about the effects of minimum coverage depth for variant and consensus calling for SAR-CoV-2, it would be great if there was a more user friendly way to test how changes to workflow parameters (min depth in particular) influences our QC metrics and outputs from artic.
