### ISSUE TITLE
artic_plot_amplicon_depth cmd missing

### ISSUE THREAD

**Issue by emiracherif** [artic-network/artic-ncov2019#58]
Hi, 
I had issues with  artic_plot_amplicon_depth (AssertionError: error: readgroup not found in provided primer scheme (1)), I tried to get the new primer scheme with artic-tools. But I had the same error.

I was using artic 1.1.3, so I updated to artic 1.2.1, and now I can't find the plotting cmd anymore!

Is the artic_plot_amplicon_depth deprecated in the new artic version? Is there a new cmd to plot amplicons coverage?

Thank you in advance for the help,

Best 
E.

**Comment by will-rowe** [comment]
Hi @emiracherif - thanks for getting in touch.

Short answer is yes - the plotting command is removed in the new artic version. Sorry for any inconvenience caused by that - it was causing a lot of trouble for some HPC users to have plotting baked in to the pipeline. The latest version of ARTIC (1.2.1) has initial support for multiqc, which will generate equivalent amplicon plots. So, you should be able to call `multiqc .` on your pipeline output directory and it will generate a report for you, containing the plot.

Feedback welcome. The upcoming release (1.3.0) of artic will have more information in the multiqc report but it is a work in progress.

**Comment by emiracherif** [comment]
Hi @will-rowe ,
Thank you very much for your reply. I'm still having some trouble, though.

I ran `multiqc . ` on one of my artic output_directories, but it seems that multiqc does not find the expected files.
So I get this warning/error: [WARNING]         multiqc : No analysis results found. Cleaning up..

Am I missing something? Or did I need to put the scheme.bed file in my output directory?

Thanks again
Emira

PS: here is the list of my output files: 
p1_barocde01.1.hdf
p1_barocde01.1.vcf
p1_barocde01.2.hdf
p1_barocde01.2.vcf
p1_barocde01.alignreport.er
p1_barocde01.alignreport.txt
p1_barocde01.consensus.fasta
p1_barocde01.coverage_mask.txt
p1_barocde01.coverage_mask.txt.1.depths
p1_barocde01.coverage_mask.txt.2.depths
p1_barocde01.fail.vcf
p1_barocde01.merged.vcf
p1_barocde01.merged.vcf.gz
p1_barocde01.merged.vcf.gz.tbi
p1_barocde01.minion.log.txt
p1_barocde01.muscle.in.fasta
p1_barocde01.muscle.out.fasta
p1_barocde01.pass.vcf.gz
p1_barocde01.pass.vcf.gz.tbi
p1_barocde01.preconsensus.fasta
p1_barocde01.primersitereport.txt
p1_barocde01.primers.vcf
p1_barocde01.primertrimmed.rg.sorted.bam
p1_barocde01.primertrimmed.rg.sorted.bam.bai
p1_barocde01.sorted.bam
p1_barocde01.sorted.bam.bai
p1_barocde01.trimmed.rg.sorted.bam
p1_barocde01.trimmed.rg.sorted.bam.bai

**Comment by will-rowe** [comment]
Sorry - I forgot that for v1.2.1 this was enabled by using `--strict` as it is a new feature and we didn't want it enabled by default (which it will be on the next release). I'm afraid you'll have to rerun with --strict and then call multiqc

**Comment by emiracherif** [comment]
Thanks! It worked great :)

**Comment by will-rowe** [comment]
Great!
