### ISSUE TITLE
Artic enviroment does not install after 7 days

### ISSUE THREAD

**Issue by gvaleman** [artic-network/artic-ncov2019#85]
Hello, I hope you ares fine.

I have an issue instaling the artic network enviroment on ubuntu 18.04.
I installed miniconda3, I cloned the files from github and I tried to install the artic network enviroment, but after 7 days installing I stoped the instalation to retry, I retried and I waited another 7 days, but the artic network enviroment did not was installed. It was "Solving enviroment" all the time.
Previuosly I installed artic network enviroment without problem in just 26 hours.
![Captura de pantalla de 2021-11-25 17-06-26](https://user-images.githubusercontent.com/95062993/143524110-3273241f-9aad-4c89-b64e-7e01fe82f5fc.png)

I wait you can help me. Thank you

**Comment by ha-ruiz75** [comment]
hi, i had success installing artic using mamba.
i had to install the mamba environment first, then use it to install the artic environment.
it only took a few minutes

**Comment by mjfos2r** [comment]
> hi, i had success installing artic using mamba. i had to install the mamba environment first, then use it to install the artic environment. it only took a few minutes

THANK YOU SO MUCH. 

after many failed attempts this is what finally got it working. the rest of my reply will be directed at others struggling to get the pipeline up and running. I'm running inside of WSL on Ubuntu20.04 so your mileage may vary but should work across other distros.

1.first install mamba
`conda install mamba -n base -c conda-forge `
2. I don't know if it's necessary but I made sure to remove the environment after my numerous failed attempts just for good measure.
`conda env remove -n artic-ncov2019`
3. then run the same create command with mamba in place of conda. The two -v flags are so that you can actually see what is going on in the background.
`mamba env create -f environment.yml -v -v`

went from several days of headache to only a few minutes.
